### ISSUE TITLE
mixinをつくる

### ISSUE THREAD

**Issue by dninomiya** [d-Tshoji/day-service#24]
mixin とは js でいう関数のようなもの。
また、sassでは変数が使えるのでカラーコードや数値を変数にして使いまわすことができる。

1. _mixin.scss を作成し、下記の内容を参考のプロジェクトに適したmixinを作成
2. media query を使う場所を、 mixin を使う形に書きなおす
3. style.scss の一番上で mixin を import

mixin.scss
```
$tablet-width: 768px; // これが変数。 sass のばあい   $xxx: xx で変数作成&代入可能
$desktop-width: 1024px;

@mixin tablet { // この書き方で tablet という mixin を作成できる
  @media (min-width: #{$tablet-width}) and (max-width: #{$desktop-width - 1px}) {
    @content;
  }
}

@mixin desktop {
  @media (min-width: #{$desktop-width}) {
    @content;
  }
}
```

xxx.scss
```
p {
  font-size: 16px;

  @include tablet { // こんな感じで使える。タブレットのときのスタイル指定
    font-size: 18px;
  }

  @include desktop {
    font-size: 20px;
  }
}
```

たとえばテーマカラーのカラーコードなど、サイト内で使いまわす色は変数にしてmixin や変数用ファイルにおいておき、それを使うほうがよい（色を覚える必要がなくなり、複数人作業で便利）

```
$primeColor = #fafafa;

body {
  color: $primeColor;
}
```

といった具合

**Comment by dninomiya** [comment]
Readme codeタブで確認できましたが、最後の方に誤字あるぽいのでこのブランチで合わせて対応もとむ

**Comment by d-Tshoji** [comment]
承知しました。

**Comment by dninomiya** [comment]
あと各種コマンドが監視になってますが、監視してるのはdefault のみで、各コマンドはコンパイル、画像については圧縮を行ってます。

別件で、defaultタスクにimagemin を含めたい。(別途叩かなくてよいように)

**Comment by deerboy** [comment]
深めたい は 含めたい の誤字

**Comment by dninomiya** [comment]
非常に素晴らしいと思います
