### ISSUE TITLE
jsのclickイベント touchstartに

### ISSUE THREAD

**Issue by dninomiya** [d-Tshoji/day-service#26]
スマホの場合 click だと効かないことがあり、かつクリックを離したときに発動するため、若干挙動にもたつきを感じる。
click イベントをすべて `touchstart` に変えたい。

また、処理のまとまりごとにコメントを書いて、他の人がある程度分かりやすいようにしたい

```
// --------------------------
// インレイ処理
// --------------------------

.....

// --------------------------
// タブ切り替え
// --------------------------

.....

```

みたいな感じ

**Comment by d-Tshoji** [comment]
```
$('.js-nav-burger').bind('touchstart', function() {
  $('.js-nav').addClass('active');
});
```
に変更した所検証でのタブレットでは作動するのですが、レスポンシブのPCだと反応しませんでした。

**Comment by dninomiya** [comment]
bind は廃止になったのでNGです on を使いましょう
1. `touchstart click` とすると両方で動くようになります
2. `$('.js-nav-burger')` へのクリックイベントが二つあるので、下のstop propagation() を上のイベントにマージしましょう
3. burget の touch start に return false が欲しいです（クリックイベント系には基本 return false をつける）
`$(document) ` (全体)への クリックイベントについては return false をつけない（全てのクリックが無効化されるため）
