### ISSUE TITLE
バグ修正#25~27

### ISSUE THREAD

**Issue by d-Tshoji** [d-Tshoji/day-service#28]
- まとめissues
- issue #25 #26 #27 を修正
- 全て終わり次第 pull request

# タスク一覧

- [x]  #27 README作成
- [x]  #26 jsのclickイベント touchstartに
- [x]  #25 タブ切り替え部分のカーソルをリンクできるように

**Comment by dninomiya** [comment]
thanks~
細かいけど コンポーネント　＝　部品なので、　タスク一覧とかのがいいかも
一番最後の３行だけでも情報としては十分です！b
あと assignees、label, milestone をお忘れなく（今は一人なのでよいが、後々チームになると誰が担当のissueかわからないため）

**Comment by dninomiya** [comment]
上記コメントしましたー

**Comment by d-Tshoji** [comment]
コメントありがとうございます。
修正させていただきました。

**Comment by dninomiya** [comment]
ないっすー
