### ISSUE TITLE
Faviconを追加する

### ISSUE THREAD

**Issue by d-Tshoji** [d-Tshoji/day-service#31]
- faviconを探すor作成する
- faviconを表示されるように設定

**Comment by dninomiya** [comment]
@d-Tshoji
参考までに
http://favicon.7zone.org/

**Comment by d-Tshoji** [comment]
@deerboy 
faviconの収納場所はsrcのimgで良いのでしょうか？(.ico)
その場合またgulpで設定して出力しないとですよね。

**Comment by d-Tshoji** [comment]
凄く悩んでたのですが、faviconはアップロードしてからじゃないと使えないのですね。
調べてみて分かりました。

**Comment by dninomiya** [comment]
ディレクトリはどこでもよですが、imgになるかなーとおもいます

**Comment by dninomiya** [comment]
http://dotinstall.com/lessons/website_html_v2/39402

**Comment by d-Tshoji** [comment]
html講座の方のfavicon導入見てました、、、
もう1度チャレンジしてきます。

**Comment by dninomiya** [comment]
ないすーーーー
