### ISSUE TITLE
firefoxでspメニューのjsが作動しない

### ISSUE THREAD

**Issue by d-Tshoji** [d-Tshoji/day-service#34]
## バグ報告
- firefoxにてバーガーメニューをクリックしても反応しない
- firefoxにて検証レスポンシブにてバーガーメニューをタッチしても反応しない
- タブ切り替えのJSは正常に作動しておりました。
***
#### エラーメッセージ
`ReferenceError: "x" is not defined`
firefoxから **変数が宣言されていない** か **スコープの誤り** と指摘されましたが、
他のブラウザで作動する以上別が原因だと思っております。

**Comment by d-Tshoji** [comment]
## やや改善報告
- 以下に書き換えた所firefoxでも作動を確認
しかしタッチシミュレーションを有効にすると開いた瞬間メニューを押してしまうbugあり
- `event.stopPropagation();`をひとまとめにしていたのが原因とみられる。
良い解決策がありましたら指摘頂けると幸いです。
- こちらも追って修正予定
```
$(".js-nav-burger").on('touchstart click', function () {
  $('.js-nav').addClass('active');
  //event.stopPropagation();
  return false;
});

$(document).on('touchstart click', function (e) {
  $('.js-nav').removeClass('active');
});

$('.js-nav').on('touchstart click', function (e) {
  event.stopPropagation();
});
//-----------------------追記---------------------------
$(".js-nav-burger").on('touchstart click', function () {
  event.stopPropagation();
});
//------------------------------------------------------
```

**Comment by dninomiya** [comment]
追記部分消して良い気が。
return false で解決してる気がする。
stopPropagation よりreturn false のが強力。

**Comment by d-Tshoji** [comment]
## 解決
firefoxにてメニュー欄を押しても閉じてしまうバグを修正
原因: 
`$('.js-nav').on('touchstart click', function (e) {`のeをeventに直した所正常に機能
IE,Chromeでは省略が可能となっていますが、firefoxだと省略が不可能のようです。
## 不具合
firefoxのレスポンシブモード、タッチシミュレートを実行すると2連続押しになってしまう。
原因: 模索中

**Comment by dninomiya** [comment]
`firefoxだと省略が不可` こういうのが当たり前になりすぎて、ついつい共有し損ねてしまうので反省・・・

brdもメニューあったのでそこ参考にしてもよいかも？

**Comment by d-Tshoji** [comment]
- ### タッチシミュレーションの件なのですが
コンソロールエラーは出てないのでシミュレーション側のタッチ判定が長い為
出た瞬間にそのままナビメニューを押しちゃっている状況だと思います。
- #### 解決策として以下を考えたのですがどうでしょうか
1. 押した後に1秒ほどディレイを設ける
2. メニューの位置自体を変える(少し位置を下げるなど)

**Comment by d-Tshoji** [comment]
## 解決
firefoxのタッチシミュレーションにてメニューを開いた瞬間押してしまう問題を解決
#### デメリット
メニューが開くまで400ミリ秒の遅延が発生する。

**Comment by dninomiya** [comment]
イベントに遅延は存在しない
2回走るのは
touchstart → 親指触れた瞬間
click → 親指触れて離した瞬間
で、2回走っていると思われる

各 click を mousedown にすることで解決しないか？ try

**Comment by d-Tshoji** [comment]
コメントありがとうございます。
さっそくtryしてみます

**Comment by d-Tshoji** [comment]
$(".js-nav-burger").on('touchstart mousedown', function () {
    $('.js-nav').addClass('active');
    return false;
});

こちらに変更しましたが、改善されませんでした。
`$(".js-nav-burger").on('touchstart', function () {`
とtouchstartのみにもしてみましたが以前開いた瞬間に押してしまいます。

- 因みにchromeのレスポンシブでは正常に機能しており
firefoxのレスポンシブタッチシミュレーションモードでのみ発生しております。

**Comment by d-Tshoji** [comment]
### 追記
```$(".js-nav-burger").on('mousedown', function () {```
で正常に機能しました。
touchstartと比べるとやや遅いですが。
___
#### 更に追記
```$(".js-nav-burger").on('click', function () {```
clickのみでもいけました。
touchstartを挟むとどうしてもすぐ反応してしまいます。

**Comment by dninomiya** [comment]
むしろすぐ反応させるために touchstart にした経緯があります。
ただ、 firefox で不具合があるようなので click に戻してもらったと。

いずれにせよOKです！お疲れ様でした！

**Comment by d-Tshoji** [comment]
お忙しいところ監督、アドバイスしていただき痛み入ります。
