### ISSUE TITLE
クライアントチェック用にサイト仮公開

### ISSUE THREAD

**Issue by dninomiya** [d-Tshoji/day-service#36]
public ディレクトリを作成し、distの中身をコピー

1. firebase account を作成 https://firebase.google.com/?hl=ja
2. firebase設定
https://firebase.google.com/docs/hosting/quickstart?hl=ja

deploy コマンド後にurlが表示されるのでそれをreadmeに記載(確認用URLとして)

終わったらfirebaseによって作成されたjsonや編集したreadmeをcommit.
なお、publicはgitignoreに含め、git対象から外す

**Comment by d-Tshoji** [comment]
## 質問
- 設定②の「デプロイする Firebase アプリを選択したら、 **プロジェクト ディレクトリ** に cd して次のコマンドを実行します。」とゆう **ディレクトリ** とは新しく#36 の **feature/36** branchを切って指定するのか、それともcheckout **master** or **develop** してpullしたディレクトリを使うべきなのか

**Comment by dninomiya** [comment]
@d-Tshoji 
develop pull した状態で issue の branch 作成し、そこでissue の手順を踏んでください！

**Comment by dninomiya** [comment]
基本新しいissue branch を作る時は必ず最新のdevelop から切るでOKです

**Comment by d-Tshoji** [comment]
設定ガイドにはない選択肢出たのですがどれでしょうか？
1か3かなとは思うのですが。
1. Database: Deploy Firebase Realtime Database Rules
1. Functions: Configure and deploy Cloud Functions
1. Hosting: Configure and deploy Firebase Hosting sites

**Comment by dninomiya** [comment]
3 ですー

**Comment by d-Tshoji** [comment]
firebeseの設定プロジェクトなので2でしょうか？
それともfirebeseの適用する新しい開発プロジェクトディレクトリをとゆう意味なのか...
? Select a default Firebase project for this directory:
1. [don't setup a default project]
1. [create a new project]

**Comment by dninomiya** [comment]
project ってまだつくってないかんじですか？ firebase 上に。
だとしたら create new project になります

**Comment by dninomiya** [comment]
お疲れ様でした！ 👍
