### ISSUE TITLE
検品

### ISSUE THREAD

**Issue by dninomiya** [d-Tshoji/day-service#4]
https://trello.com/c/wwM7Tf8P

**Comment by d-Tshoji** [comment]
Firefoxにて混在アクティブコンテンツにて
`“http://fonts.googleapis.com/earlyaccess/notosansjp.css” の読み込みをブロックしました`
以前とと同じhttps:じゃないため読み込めてない可能性？

**Comment by dninomiya** [comment]
こちらにそって url と font指定書き換えてもらいたく！
https://fonts.google.com/earlyaccess#Noto+Sans+JP

**Comment by dninomiya** [comment]
これ終わりまひたっけ

**Comment by d-Tshoji** [comment]
以前チャットで書いたのですが自分windowsなので
PCでSafari確認できないのでそこだけチェックできてないです。
テストの結果(trelloにコメ)を改善等しないのであれば終わってます。

**Comment by dninomiya** [comment]
了解です！かくにんします

**Comment by dninomiya** [comment]
@d-Tshoji 

https://github.com/deerboy/training/wiki/Validation

こちらのゴールの基準に沿って対応をお願いします。
validator は情報欄は対応不要で、エラーの欄だけ対応をお願いします。
エラー文が英語ですがググると解決策や原因でてきます（かなり単純なエラーなので大丈夫かと）

page speed はグリーンが理想ですが、なかなか出せる人はいないです。
今回程度の案件であればイエローでも良いですが、グリーンにする方法を伝えるだけ伝えるので、対応はお任せします

gulp で画像圧縮（より強く）、 gzip 圧縮　のgulpプラグインを入れ、圧縮タスクを作成。build時に圧縮が走るようにする

以上、よろしくお願いします！
