### ISSUE TITLE
js タブの切り替えが無効になっている。

### ISSUE THREAD

**Issue by d-Tshoji** [d-Tshoji/day-service#55]
- テストテキスト全て同じの為気付いてなかったが、
ラベルが切り替わっていない事に気付き発覚
- 要調査

**Comment by dninomiya** [comment]
失礼。こちらのリファクタのタイミングで殺してしまった説。
js- のトリガー名が変わっている可能性あるので見てみてください

**Comment by d-Tshoji** [comment]
了解です、一通りIssue立て終えたら対処に当たります。

**Comment by d-Tshoji** [comment]
#54 に吸収

**Comment by dninomiya** [comment]
おつかれした！
