### ISSUE TITLE
safari Ihone7 GoogleMapの不具合

### ISSUE THREAD

**Issue by d-Tshoji** [d-Tshoji/day-service#56]
- ## GoogleMapが650x450指定のwidth100%に設定されていることが原因？
![ihone7-training](https://user-images.githubusercontent.com/29697085/30257484-6b7dab44-96ed-11e7-8666-7a5ae7632f91.jpg)

**Comment by dninomiya** [comment]
```
.facility-map {
  margin-top: 50px;
  height: 150px;
  @include desktop() {
    width: 100%;
    vertical-align: bottom;
    height: 300px;
    pointer-events: none;
  }
```

desktop のときしか width 100% あたらないのが原因

**Comment by d-Tshoji** [comment]
#54 に吸収

**Comment by dninomiya** [comment]
おつかれした！
